version: '3.2'

services:
  # Base de données MySQL
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./csv_data:/csv_data
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: dolibarr_user
      MYSQL_PASSWORD: dolibarr_password
    networks:
      dolibarr_network:
        ipv4_address: 192.168.1.2

  # Dolibarr
  dolibarr:
    image: tuxgasy/dolibarr:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - DOLI_DB_DRIVER=mysql
      - DOLI_DB_HOST=db
      - DOLI_DB_PORT=3306
      - DOLI_DB_USER=dolibarr_user
      - DOLI_DB_PASSWORD=dolibarr_password
      - DOLI_DB_NAME=dolibarr
    networks:
      dolibarr_network:
        ipv4_address: 192.168.1.3
    volumes:
      - dolibarr_data:/var/www/htdocs

networks:
  dolibarr_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  db_data:
  dolibarr_data:
